// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDn8a71uITpcAup8SAZpXto6wcD4ZOe7w',
    appId: '1:1091099738393:web:fc68bc65401218b29f0588',
    messagingSenderId: '1091099738393',
    projectId: 'rumahsakitapp-47af1',
    authDomain: 'rumahsakitapp-47af1.firebaseapp.com',
    storageBucket: 'rumahsakitapp-47af1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvZokkPOp70yqs4mzXOvy1B2nzfGea4sg',
    appId: '1:1091099738393:android:7af124a3fcc2f5f99f0588',
    messagingSenderId: '1091099738393',
    projectId: 'rumahsakitapp-47af1',
    storageBucket: 'rumahsakitapp-47af1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdr7BQaHFYR1LCeSeHf2jyMRLPiwZjbg',
    appId: '1:1091099738393:ios:5d5254ca67a4a0749f0588',
    messagingSenderId: '1091099738393',
    projectId: 'rumahsakitapp-47af1',
    storageBucket: 'rumahsakitapp-47af1.firebasestorage.app',
    iosBundleId: 'com.example.rumahsakitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADdr7BQaHFYR1LCeSeHf2jyMRLPiwZjbg',
    appId: '1:1091099738393:ios:5d5254ca67a4a0749f0588',
    messagingSenderId: '1091099738393',
    projectId: 'rumahsakitapp-47af1',
    storageBucket: 'rumahsakitapp-47af1.firebasestorage.app',
    iosBundleId: 'com.example.rumahsakitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDn8a71uITpcAup8SAZpXto6wcD4ZOe7w',
    appId: '1:1091099738393:web:f7538a035296ff569f0588',
    messagingSenderId: '1091099738393',
    projectId: 'rumahsakitapp-47af1',
    authDomain: 'rumahsakitapp-47af1.firebaseapp.com',
    storageBucket: 'rumahsakitapp-47af1.firebasestorage.app',
  );
}
